#!/bin/sh

# PROVIDE: secure_proxy
# REQUIRE: LOGIN cleanvar

#
# Add the following to /etc/rc.conf to enable secure-proxy:
#
# secure_proxy_enable (bool):   Set to "NO" by default.
#                               Set it to "YES" to enable secure-proxy
# secure_proxy_path (str):      Set to "/usr/local/secure-proxy" by default.
#                               Set it the installation path
#

. /etc/rc.subr

: ${secure_proxy_enable="NO"}
: ${secure_proxy_path="/usr/local/secure-proxy"}
: ${secure_proxy_options=""}

name="secure_proxy"
rcvar=`set_rcvar`

load_rc_config $name

pidfile="/var/run/$name.pid"
command="/usr/sbin/daemon"
command_args="-P $pidfile /usr/local/bin/node $secure_proxy_path/src/index.js start"

run_rc_command "$1"
